version: "3"
services:
  keto:
    image: oryd/keto:v0.11.1-alpha.0
    ports:
      - "4466:4466"
      - "4467:4467"
    command: serve -c /home/ory/keto.yml
    restart: on-failure
    environment:
      - NAMESPACES_LOCATION=file:///home/ory/namespaces.keto.ts
    volumes:
      - type: bind
        source: config/keto.yml
        target: /home/ory/keto.yml
      - type: bind
        source: ./namespaces.keto.ts
        target: /home/ory/namespaces.keto.ts