name: Test policies, build bundle and upload
on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Test build and upload
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: latest

    - name: Run OPA Tests
      run: opa test policies -v

    - name: Retrieve latest GraphQL Schema
      env:
        APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      run: |
        # install rover CLI
        curl -sSL https://rover.apollo.dev/nix/latest | sh
        export PATH="/home/runner/.rover/bin:$PATH"
        # Retrieve and save schema
        rover graph fetch hub-dev@current --skip-update-check --output plain > schema.graphql

    - name: Build bundle
      if: success()
      run: |
        json_schema_path=policies/graphql/data.json
        schema_raw=$(python3 clean-schema.py schema.graphql) && \
        jq --null-input --arg data "$schema_raw" '.schema |= $data' > "$json_schema_path" && \
        opa build -b policies 

    - name: Upload bundle
      if: success()
      uses: keithweaver/aws-s3-github-action@v1.0.0
      with:
        command: cp
        source: ./bundle.tar.gz
        destination: s3://${{ secrets.AWS_BUCKET }}/bundle.tar.gz
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }} 
